trip service test
galbavyj/PA165-Travel-Agency-I pull request #26
Opened 2016-11-20 18:37 UTC by MartinMatko

trip service test

2016-11-21 18:21 UTC, behramip submitted a review, later dismissed

2016-11-21 18:54 UTC, deezad commented on TravelAgencyService/src/test/java/cz/muni/fi/pa165/travelagency/travelagencyservice/TripServiceTest.java
> +    public void removeTrip(Trip trip){
netestuje remove?

2016-11-21 19:03 UTC, deezad commented on TravelAgencyService/src/test/java/cz/muni/fi/pa165/travelagency/travelagencyservice/TripServiceTest.java
> +        assertEquals(tripService.findAllTrips(), Arrays.asList(trip2));
tady by asi mělo být tripService.findTripsByCountry() ?

2016-11-21 21:30 UTC, galbavyj requested changes

2016-11-21 21:30 UTC, galbavyj commented on TravelAgencyService/src/test/java/cz/muni/fi/pa165/travelagency/travelagencyservice/TripServiceTest.java
> +    public void removeTrip(Trip trip){
Testuješ to isté, čo v createTrip().

2016-11-22 18:33 UTC, behramip requested changes

2016-11-22 18:33 UTC, behramip commented on TravelAgencyService/src/test/java/cz/muni/fi/pa165/travelagency/travelagencyservice/TripServiceTest.java
> +        assertEquals(tripService.findAllTrips(), Arrays.asList(trip2));
tady by asi mělo být tripService.findTripsByCountry() ?

2016-11-22 18:33 UTC, behramip commented on TravelAgencyService/src/test/java/cz/muni/fi/pa165/travelagency/travelagencyservice/TripServiceTest.java
> +    public void removeTrip(Trip trip){
netestuje remove?

2016-11-24 08:26 UTC, merged